### ISSUE TITLE
Example with images

### ISSUE THREAD

**Issue by n1xx1** [enzedonline/quill-blot-formatter2#1]
Thanks for keeping this package updated!

I'm having some issues integrating it in my project. This is what I currently have:

```ts
import BlotFormatter2 from "@enzedonline/quill-blot-formatter2";
import { ForwardedRef, forwardRef, useEffect, useRef } from "react";
import { Quill } from "react-quill-new";

const BlockEmbed = Quill.import("blots/block/embed") as any;

class ImageBlot extends BlockEmbed {
  static blotName = "image";
  static tagName = "img";

  static create(value: any) {
    let node = super.create();
    node.setAttribute("src", value.url);
    node.setAttribute("alt", value.alt);
    node.setAttribute("height", value.height);
    node.setAttribute("width", value.width);
    node.setAttribute("style", value.style);
    return node;
  }

  static value(node: any) {
    return {
      url: node.getAttribute("src"),
      alt: node.getAttribute("alt"),
      height: node.getAttribute("height"),
      width: node.getAttribute("width"),
      style: node.getAttribute("style"),
    };
  }
}

Quill.register(ImageBlot);

Quill.register("modules/blotFormatter2", BlotFormatter2);
```

I'm using quill 2 with [react-quill-new](https://www.npmjs.com/package/react-quill-new) and I followed [this guide](https://quilljs.com/docs/guides/cloning-medium-with-parchment#images) to implement an ImageBlot. However after I embed an image with something like this:

```ts
editor.insertEmbed(
  insertSelection.current.index,
  "image",
  { alt: "Image", url: imageUrl },
  "user",
);
```

And try to click over it I get this error:

```
TypeError: blot.parent.formats is not a function
    at DefaultAligner.isAligned (DefaultAligner.js:51:59)
    at DefaultToolbar.preselectButton (DefaultToolbar.js:69:21)
    at eval (DefaultToolbar.js:54:18)
    at Array.forEach (<anonymous>)
    at DefaultToolbar.addButtons (DefaultToolbar.js:47:33)
    at DefaultToolbar.create (DefaultToolbar.js:16:14)
    at AlignAction.onCreate (AlignAction.js:16:38)
    at eval (BlotFormatter.js:55:20)
    at Array.map (<anonymous>)
    at BlotFormatter.createActions (BlotFormatter.js:54:42)
    at BlotFormatter.show (BlotFormatter.js:36:14)
    at ImageSpec.onClick (ImageSpec.js:16:28)
```

It looks like blot.parent is a ScrollBlot and it has no formats method.

<https://github.com/enzedonline/quill-blot-formatter2/blob/master/src/actions/align/DefaultAligner.ts#L59>

What is the correct way to use the plugin?

**Comment by enzedonline** [comment]
The code in that documentation example doesn't look right to me. The image blot is an inline blot rather than a block blot. You can see their own [implementation here](https://github.com/slab/quill/blob/main/packages/quill/src/formats/image.ts).

It's not actually necessary to create an image or video blot with this tough, you can just use the native Quill blots.

Pure JS example:
```javascript
Quill.register('modules/blotFormatter2', QuillBlotFormatter2.default);
const quill = new Quill('#editor', {
  modules: {
    toolbar: [
      [{ header: [1, 2, false] }],
      ['bold', 'italic', 'underline'],
      ['image', 'video'],
    ],
    blotFormatter2: {},
  },
  placeholder: 'Compose an epic...',
  theme: 'snow', // or 'bubble'
});
```
[CodePen](https://codepen.io/enzedonline/pen/bGPgqeG)

I'll take a look at the `IsAligned()` function and see if it can be modified to handle custom blots better. To be honest, the custom blot handling code is a leftover from the old version and, other than being converted to TypeScript, I left it alone as I concentrated on the native Quill image and video formats. I have an update almost ready which adds a modal form for images to edit alt & title attributes, if there's an improvement in the custom blot handling I can make, I'll add it in there. I'll let you know here when that's up.

**Comment by n1xx1** [comment]
Yep, wrong blot, working correctly now, thank you!

**Comment by enzedonline** [comment]
Great, glad you got it fixed.

It did prompt me to rewrite that bit of logic. Next release will look at blot scope instead of blot tag type to handle inline vs block.

**Comment by enzedonline** [comment]
v2.1 released today with that logic update. Also includes support for alt/title & captions for images.
