### ISSUE TITLE
The image width is not displaying correctly after rendering in the editor.

### ISSUE THREAD

**Issue by AZCodingAccount** [enzedonline/quill-blot-formatter2#13]
Hey. This time my issue is that I've adjusted the image alignment and width using a URL format, but when I render it in Quill, it still keeps the max-width and fills the entire editor. After I click the alignment button, the width returns to normal. The root cause seems to be an extra layer of tags. How can I solve this?
default html(adjusted width don't work)：
![image](https://github.com/user-attachments/assets/b20a09f2-1b3e-43f6-9f14-a4dca76ec559)
after  click align button html：
<img width="1342" alt="image" src="https://github.com/user-attachments/assets/cc4ead25-f222-40a8-85d9-8d5410a4341f">

**Comment by enzedonline** [comment]
Something odd going on with the first example too, `--resize-width` should match the img `width` ...

I can't replicate this on my own setup. Can you let me know your settings for blot formatter and the steps you take to get this condition? (i.e. from an empty quill editor).

Thanks.

**Comment by enzedonline** [comment]
Hmm. Ok, I found one bug which might explain the first issue of the 100% width. If the img has a width attribute without dimensions, this is copied into the `--resize-width` but this isn't recognised in the browser as a valid width style value without dimensions. So setting the alignment without resizing causes the image to go full width in that case.
e.g. 
```html
<img src="https://cdn11.bigcommerce.com/s-wfrpmvke08/images/stencil/250x69/tradedepot-logo_v7_250x69px_1715221926__33872.original.png" alt="Trade Depot" height="84" width="250" title="Trade Depot">
```

Using centre alignment goes to:
```html
<span class="ql-image-align-center" contenteditable="false" data-relative-size="false" style="--resize-width: 250;">
<img src="https://cdn11.bigcommerce.com/s-wfrpmvke08/images/stencil/250x69/tradedepot-logo_v7_250x69px_1715221926__33872.original.png" alt="Trade Depot" height="84" width="250" data-blot-align="center">
</span>
```
![image](https://github.com/user-attachments/assets/510e6418-6695-4f59-b44a-aa09dd45f778)

If I set `--resize-width: 250px;`, it displays correctly. 

I'll fix that for now and wait for your info on the second issue.

**Comment by enzedonline** [comment]
Needed a small adjustment in the image and iframe align formats. 
Can you  test from compiled js? https://drive.google.com/file/d/1KwegAvyJ17ptHL-76R7t68Ph6H9Ae8u5/view?usp=sharing

**Comment by AZCodingAccount** [comment]
> Hmm. Ok, I found one bug which might explain the first issue of the 100% width. If the img has a width attribute without dimensions, this is copied into the `--resize-width` but this isn't recognised in the browser as a valid width style value without dimensions. So setting the alignment without resizing causes the image to go full width in that case. e.g.
> 
> ```
> <img src="https://cdn11.bigcommerce.com/s-wfrpmvke08/images/stencil/250x69/tradedepot-logo_v7_250x69px_1715221926__33872.original.png" alt="Trade Depot" height="84" width="250" title="Trade Depot">
> ```
> 
> Using centre alignment goes to:
> 
> ```
> <span class="ql-image-align-center" contenteditable="false" data-relative-size="false" style="--resize-width: 250;">
> <img src="https://cdn11.bigcommerce.com/s-wfrpmvke08/images/stencil/250x69/tradedepot-logo_v7_250x69px_1715221926__33872.original.png" alt="Trade Depot" height="84" width="250" data-blot-align="center">
> </span>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/72310199/378641957-510e6418-6695-4f59-b44a-aa09dd45f778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjQzMjksIm5iZiI6MTcyOTU2NDAyOSwicGF0aCI6Ii83MjMxMDE5OS8zNzg2NDE5NTctNTEwZTY0MTgtNjY5NS00ZjU5LWI0NGEtYWEwOWRkNDVmNzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDAyMjcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOWU4ZTcwZmVjZjVmZGUwOTlkY2Y4OTQxZTFmMDE0ZTY5Yzc5OTA3OGY5NjVjZDJlOTk4YjUzYjU5ODQ2NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RfiJxBWAuvAc36bj4jz_zRtYes5UocDWRVs-DyTdYEY)
> 
> If I set `--resize-width: 250px;`, it displays correctly.
> 
> I'll fix that for now and wait for your info on the second issue.

key, the first image has an issue. When I click the center-align button, it turns into the second image, which then displays correctly.second issue not a error

**Comment by AZCodingAccount** [comment]
Have you fixed the issue with the first image? Please keep me updated on any progress.

**Comment by AZCodingAccount** [comment]
> Something odd going on with the first example too, `--resize-width` should match the img `width` ...
> 
> I can't replicate this on my own setup. Can you let me know your settings for blot formatter and the steps you take to get this condition? (i.e. from an empty quill editor).
> 
> Probably a good idea to include the css styles your using for your `ql-image-align-xx` classes and the img tag before any formatting/resizing has happened.
> 
> Thanks.

i just adjust width,then when i get the html to render again, i get the error

**Comment by enzedonline** [comment]
Ahhh .. forget that test for now. Quill does some odd things with it's delta format. When the image is nested inside other inline elements and the editor loads content from delta it calls the format for each element over and over. 
```html
<p>
  <u style="color: rgb(117, 117, 117); background-color: rgb(255, 255, 255);">
    <a href="https://tradedepot.co.nz/" rel="noopener noreferrer" target="_blank">
      <img src="https://cdn11.bigcommerce.com/s-wfrpmvke08/images/stencil/250x69/tradedepot-logo_v7_250x69px_1715221926__33872.original.png" alt="Trade Depot" height="84" width="250" title="Trade Depot">
    </a>
  </u>
</p>
```

The format expects the node to be the span wrapper, which it is the first time it's called, but then it gets called again for a `<a>` and `<u>` tags, even though it's all one delta entry. 

Before reloading, the format is correct:
```html
<p>
  <u style="color: rgb(117, 117, 117); background-color: rgb(255, 255, 255);">
    <a href="https://tradedepot.co.nz/" rel="noopener noreferrer" target="_blank">
      <span class="ql-image-align-center" contenteditable="false" data-title="Trade Depot" data-relative-size="false" style="--resize-width: 250px;">
        <img src="https://cdn11.bigcommerce.com/s-wfrpmvke08/images/stencil/250x69/tradedepot-logo_v7_250x69px_1715221926__33872.original.png" alt="Trade Depot" height="84" width="250" title="Trade Depot" data-blot-align="center">
      </span>
    </a>
  </u>
</p>
```

After reloading, the `data-blot-align` is assigned to the wrong element (the `<a>` tag), the class, `--resize-width`, `data-title` & `relative-size` go to the outer `<u>` and the span wrapper has gone completely.
```html
<p>
  <u class="ql-image-align-center" contenteditable="false" data-title="Trade Depot" data-relative-size="false" style="--resize-width: 250px; color: rgb(117, 117, 117); background-color: rgb(255, 255, 255);">
    <a href="https://tradedepot.co.nz/" rel="nofollow noopener" target="_blank" contenteditable="false" data-title="Trade Depot" data-relative-size="false" style="--resize-width: 250px;" data-blot-align="center" width="250px">
      <img src="https://cdn11.bigcommerce.com/s-wfrpmvke08/images/stencil/250x69/tradedepot-logo_v7_250x69px_1715221926__33872.original.png" alt="Trade Depot" height="84" width="250" title="Trade Depot">
    </a>
  </u>
</p>
```

I'll need to take a look at how to stop this tomorrow. Quill is really, really frustrating to work with ... the delta should just restore the markup exactly as it is.

**Comment by enzedonline** [comment]
That still doesn't relate to your issue though since your image isn't nested. You'll need to give me a more clear set of steps to reproduce, and also what your settings and css look like.

**Comment by AZCodingAccount** [comment]
I adjusted the image width and stored the HTML string in the database. When retrieving it from the database and rendering it again, a problem occurred. You were right; the issue was due to improperly nested tags.

**Comment by enzedonline** [comment]
There is no css shown in the first 2 pics .. and there must be some other step, there is a color style on the image - where does this come from? 
I can't help you if I don't know the steps you take to replicate this with. Start from an empty Quill editor, tell me the complete set of steps to reach this point.

**Comment by AZCodingAccount** [comment]
no no no,it seems to be an issue with Quill rendering HTML. I've solved it by directly manipulating the DOM elements. Here's the solution in code:
```javascript
// 修复图片缩放插件的问题
const initializeImageSizes = () => {
  // 获取所有以 ql-image-align- 开头的元素
  const imageContainers = document.querySelectorAll(
    '[class^="ql-image-align-"]'
  )

  imageContainers.forEach((container) => {
    // 在每个容器中查找 img 标签
    const img = container.querySelector('img')
    if (img) {
      // 获取 img 的 width 属性值
      let width = img.getAttribute('width')

      // 如果找到了有效的宽度，直接设置 --resize-width
      if (width) {
        // 确保百分比值后面有 % 符号
        if (!width.endsWith('%') && !width.endsWith('px')) {
          width += 'px'
        }
        container.style.setProperty('--resize-width', width)
      }
    }
  })
}
```

**Comment by ttsandberg** [comment]
I'm not completely sure if this is related but I'm also seeing incorrect width for images when trying to render from html, but only when the alignment is set. It seems like its setting the width of the image to the width within the imageAlign attribute (which is getting set to the original width of the image) instead of using the `--resize-width`, even with the css provided. Calling the function @AZCodingAccount provided after the image is rendered does fix the issue, but it would be ideal if it just used the correct width it was resized to so there doesnt need to be dom manipulation after it is rendered.

Heres a codepen showcasing when there is a span with the class ql-image-align-center it does not use --resize-width or the explicit width set on the image when rendering the html: https://codepen.io/ttsandberg/pen/MWNBRrm. This html is what gets exported by getSemanticHTML.

Let me know if I'm missing something though, I dont completely follow what is going on in AlignFormats which is where I'm assuming the width gets reset to the original?

**Comment by enzedonline** [comment]
I couldn't see the problem you're referring to in the code pen sorry. The `--resize-width` should just replicate whatever the image `width` attribute has. If there is no `width` attribute when the image is aligned, this will be set to the natural width. If you resize the image while it is aligned, the `--resize-width` will be updated as well as the image `width` attribute.

There is a bug that happens in the current release when the image `width` attribute has no dimensions (i.e. just a number). A pure numeric value isn't valid for a width style attribute. I have a fix ready to go for that (it just adds 'px' if the value is numeric). 

I was holding off releasing that until I try to sort another I picked up in this test - when the image is wrapped with an inline format such as `link` or `color`, it formats correctly, but when reloading from the delta, Quill overwrites any formats with the inline styles only. Their developer docs are awful, I haven't found anything describing the mechanism going on here and how I can prevent this. I may just have to make the alignment exclusive and remove any other formats if applied.

**Comment by enzedonline** [comment]
That was a wrestle. The fix for the nested elements is to check if the node is a span. If not, if the first child is the span wrapper, reapply the format to the image element, otherwise just return true. The problem was caused by Quill inline formats merging elements and blowing away the span put in by the class attributor. When that happens, the align information is lost. 

Once I've got a chance to tidy the code and make some more tests I'll have a release ready.

**Comment by enzedonline** [comment]
@ttsandberg Can you test from compiled js? I have an updated library [here](https://1drv.ms/f/s!AppilyLm3gHit4dluxCw6G0Yh2JcmA?e=wgkF3D) - let me know if this resolves your issue. Thanks.

**Comment by ttsandberg** [comment]
Thanks for taking a look! It seems like it still uses the original image width with the updated minified js. Just to clarify the issue I'm seeing, when I call `dangerouslyPasteHTML` on this html
```
<p><span class="ql-image-align-center" contenteditable="false" data-relative-size="false" style="--resize-width: 260px;"><img src="https://images.ctfassets.net/440y9b545yd9/34T8RDHUaiSX4GitevaI9G/5d0fd0892ad6883f762338481584c068/wacky_dog850.webp" width="260px" height="auto" data-blot-align="center"></span></p>
```

It renders in quill with the original image width instead as
```
<p><span class="ql-image-align-center" contenteditable="false" data-relative-size="false" style="--resize-width: 850px;"><img src="https://images.ctfassets.net/440y9b545yd9/34T8RDHUaiSX4GitevaI9G/5d0fd0892ad6883f762338481584c068/wacky_dog850.webp" data-blot-align="center" width="850px" height="auto"></span></p>
```
which is how its behaving in the codepen I linked for me at least, let me know if you dont see that on your end or if thats expected behavior.

<img width="1654" alt="Screenshot 2024-11-05 at 4 44 31 PM" src="https://github.com/user-attachments/assets/8e3913cd-7dd3-466a-9782-96f00e0db5b8">


Since the html does have explicit 'px' dimensions and theres no inline formatting wrapping the image it doesnt seem like its actually related to the fix here. I did try and track down where the pasted html's width gets reset, and at least on my end it seems like its not able to find the width attribute on the image when add is called here: https://github.com/enzedonline/quill-blot-formatter2/blob/master/src/actions/align/AlignFormats.ts#L104. Not really sure why though, if you're able to replicate it or have any insight let me know, otherwise I guess it could be an issue on my end.

**Comment by AZCodingAccount** [comment]
> Thanks for taking a look! It seems like it still uses the original image width with the updated minified js. Just to clarify the issue I'm seeing, when I call `dangerouslyPasteHTML` on this html
> 
> ```
> <p><span class="ql-image-align-center" contenteditable="false" data-relative-size="false" style="--resize-width: 260px;"><img src="https://images.ctfassets.net/440y9b545yd9/34T8RDHUaiSX4GitevaI9G/5d0fd0892ad6883f762338481584c068/wacky_dog850.webp" width="260px" height="auto" data-blot-align="center"></span></p>
> ```
> 
> It renders in quill with the original image width instead as
> 
> ```
> <p><span class="ql-image-align-center" contenteditable="false" data-relative-size="false" style="--resize-width: 850px;"><img src="https://images.ctfassets.net/440y9b545yd9/34T8RDHUaiSX4GitevaI9G/5d0fd0892ad6883f762338481584c068/wacky_dog850.webp" data-blot-align="center" width="850px" height="auto"></span></p>
> ```
> 
> which is how its behaving in the codepen I linked for me at least, let me know if you dont see that on your end or if thats expected behavior.
> 
> <img alt="Screenshot 2024-11-05 at 4 44 31 PM" width="1654" src="https://private-user-images.githubusercontent.com/171377160/383367232-8e3913cd-7dd3-466a-9782-96f00e0db5b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NjE5NjksIm5iZiI6MTczMDk2MTY2OSwicGF0aCI6Ii8xNzEzNzcxNjAvMzgzMzY3MjMyLThlMzkxM2NkLTdkZDMtNDY2YS05NzgyLTk2ZjAwZTBkYjViOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwNjQxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWYyNzdkMDU1Y2M5YzdhYmEwODBkNDViYjQ5NTJlNjAwMjkwNDJlYzhiODU1NDkzYjJiYWE2ZTFjMzkxZmRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6tCpAptZG9AoDzbxAK8JqwfknSDAZs16MGGeKmJkTpI">
> Since the html does have explicit 'px' dimensions and theres no inline formatting wrapping the image it doesnt seem like its actually related to the fix here. I did try and track down where the pasted html's width gets reset, and at least on my end it seems like its not able to find the width attribute on the image when add is called here: https://github.com/enzedonline/quill-blot-formatter2/blob/master/src/actions/align/AlignFormats.ts#L104. Not really sure why though, if you're able to replicate it or have any insight let me know, otherwise I guess it could be an issue on my end.

btw, you can try to annotation follow code,this solution my question, of course , you also should  add my patch
![image](https://github.com/user-attachments/assets/9c950b05-ed76-44ff-9299-0041d7344723)

**Comment by enzedonline** [comment]
@ttsandberg The issue lurked in the value method. Quill calls the add method twice and the value method 10x  when issuing your dangerouslyPasteHTML(). On about the 6th or 7th time, the <img> tag is empty. My code here was presuming an empty width value here meant no width attribute was supplied - this is the case normally, but for some reason, dangerouslyPasteHTML() seems to work in another way.

I've added a class method that reads and sets the width which is called from add and value, including from image.onload. The dog pic renders at the right dimensions now.

I've added some other bug fixes I've found from this. Next release will include these fixes:
- When image was aligned with other Quill inline styles applied, alignments would get knocked out by other styles when reloading editor from delta or when using `dangerouslyPasteHTML()` (Quill inline styles merge elements). Bug fix reapplies alignment format on image for first wrapped style if encountered to reestablish span wrapper.
- In some cases, if the image was not yet loaded while the format was applied, the width would be set to natural width regardless of pre-existing width attribute. Width is now read on image load in those cases.
- If image width attribute was purely numeric (ie without dimensions), aligning image would cause image to be displayed full width (due to numeric values being invalid for style width attributes). Style width now gets 'px' appended if no units in image width attribute.
- Click event on linked image was opening link during editing. Click event no longer propagates.
- Updated CSS to remove text decoration on linked image: caused image caption to be underlined in those cases.
- If image only item in editor, add new paragraph underneath when formatting from toolbar, otherwise unable to place cursor in editor.

You can test with the compiled code [here](https://1drv.ms/f/s!AppilyLm3gHit4dluxCw6G0Yh2JcmA?e=BToK5r). Let me know if that solves your issue.

@AZCodingAccount - you never gave me a reproducible example to work from despite me twice asking for that, could have saved a lot of time if you'd just given me that at the beginning ... I'm not just going to randomly patch the code when I have nothing to work from or test against.

**Comment by AZCodingAccount** [comment]
emmmm, Although I resolved this issue using my own approach, I'm glad to see that this problem has been fixed anyway. Actually, I think my description was clear enough.🤣

**Comment by enzedonline** [comment]
Your description: "I've adjusted the image alignment and width using a URL format, but when I render it in Quill, it still keeps the max-width and fills the entire editor." and "i just adjust width,then when i get the html to render again, i get the error". 

How is this a clear description? This is demonstrably not reproducible from this description - if the bug came from this action, it would have been encountered long before the package was ever published. I've not been able to reproduce it from any scenario I can think of. You haven't given me any means to reproduce this, told me the steps you took, what css you use (despite you insisting it was in the OP - it's not), how you add the image, what other formats you've applied to the image (from the original post, it's clear the color format is present but you make no mention of that anywhere.

Glad you find wasting people's time so funny.
