### ISSUE TITLE
iFrame video not resizeable?

### ISSUE THREAD

**Issue by bubbleheadinc** [enzedonline/quill-blot-formatter2#3]
Hi, thanks for your work on this lib! 

Image resizing is working great, but iframe videos don't. Should videos be able to be resized? I see `data-blot-formatter-unclickable-bound="true"` is set on the iframe. Is that to prevent play so it can be resized or is that to prevent resize? Am I missing something obvious?

![Screenshot 2024-08-03 at 11 19 23 AM](https://github.com/user-attachments/assets/183701c7-0cde-454d-a12b-db498eea8d02)

Thanks for your time!

**Comment by enzedonline** [comment]
Hi. Are you using the v2.1.2 code from the repository or the published version (v2.1.1)? I didn't quite get to finishing testing the v2.1.2 code yet (which is why it isn't published yet). v2.1.1 should resize iframes fine ([Code Pen](https://codepen.io/enzedonline/pen/bGPgqeG)). 

There is a change in 2.1.2 that dismisses the overlay if you click outside of the editor, but I missed the fact that the thumbnail overlay for iframes is created at the end of the doc body - this is what gets clicked on when you click the video embed. I'll update it first thing Monday morning before I publish the new version.

The `data-blot-formatter-unclickable-bound="true"` is just for handling the thumbnail click events.

I'll let you know here when it's up.

**Comment by enzedonline** [comment]
I've updated the repository with the beta fix - I just need to do a complete round of testing before it's published. There's a small tweak to the css included that I also picked up, taking fit-content out of iframe-align-center - some YouTube videos weren't resizing properly with this (it's only needed for the inline image format).

**Comment by enzedonline** [comment]
Good points! I've included those in the new version.

1. I've added a note to the readme re the proxy image - I didn't include it in the css as it has the potential to interfere with other elements, particularly with toolbars (it needs a lower `z-index` than the toolbar in case the proxy image scrolls up, or it needs the quill container to have overflow hidden). I've left it as a conscious design decision.
2. I've changed the proxy image logic to only create an image if one doesn't already exist. In your case, it will leave one proxy image once the modal is dismissed but no more. I looked at removing if the editor is destroyed - too much potential for breakage and it means expanding the scope to introduce a document mutation observer. Better to keep it simple. If you need the image gone completely you can add a call to your modal dismissal to remove any `'img.blot-formatter__proxy-image'` remaining.
3. I could replicate your overlay issue by making the quill root scrollable with a max-height. I've added listeners for scroll and resize on the `quill.root` element (`.ql-editor`) which will reposition the overlay in response. I couldn't see which was your scrolling element in the vid - in case it's not the `quill.root`, you can add your own scroll listener and call `repositionOverlay()` on the blot formatter instance. The overlay sits in the `quill.container` element - I'd recommend setting `overlay: hidden;` on that one to ensure the overlay isn't displayed beyond the editor.

That's all published in 2.1.2 now.

https://github.com/user-attachments/assets/b0c39080-e7a9-4b34-9376-4f6126aaebdf

**Comment by enzedonline** [comment]
Hmmm, I can't find anything in the code that expects the iframe to be a direct child of the editor. The overlay is positioned relative to the quill container:
```javascript
    const parent: HTMLElement = this.quill.root.parentNode;
    const specRect = overlayTarget.getBoundingClientRect();
    const parentRect = parent.getBoundingClientRect();

    Object.assign(this.overlay.style, {
      display: 'block',
      left: `${specRect.left - parentRect.left - 1 + parent.scrollLeft}px`,
      top: `${specRect.top - parentRect.top + parent.scrollTop}px`,
      width: `${specRect.width}px`,
      height: `${specRect.height}px`,
    });
```
The proxy is repositioned whenever the mouse hovers over an iframe.
The mouse click event that activates the overlay is dependent on the clicked target being an image:
```javascript
  onClick = (event: MouseEvent) => {
    const el = event.target;
    if (!(el instanceof HTMLElement) || el.tagName !== 'IMG') {
      return;
    }

    this.img = el;
    this.formatter.show(this);
  };
```
If you add a visible border to the proxy image, do you see it align with the iframe on mouse hover?

**Comment by enzedonline** [comment]
I think [this is it](https://github.com/enzedonline/quill-blot-formatter2/blob/cf4587a27154a1299ac4b08c275f3bd0b9a4a726/src/specs/IframeVideoSpec.ts#L6) (I haven't noticed this before, it's from the original code). 
```javascript
export default class IframeVideoSpec extends UnclickableBlotSpec {
  constructor(formatter: BlotFormatter) {
    super(formatter, 'iframe.ql-video');
  }
}
```

It causes the `IframeVideoSpec` to look for elements matching `'iframe.ql-video'` and sets the mouseenter event listeners on elements that match that.
https://github.com/enzedonline/quill-blot-formatter2/blob/cf4587a27154a1299ac4b08c275f3bd0b9a4a726/src/specs/UnclickableBlotSpec.ts#L94C1-L101C5
```javascript
onTextChange = () => {
    Array.from(document.querySelectorAll(this.selector))
      .filter((element): element is HTMLElement => !(element.hasAttribute(MOUSE_ENTER_ATTRIBUTE)))
      .forEach((unclickable) => {
        unclickable.setAttribute(MOUSE_ENTER_ATTRIBUTE, 'true');
        unclickable.addEventListener('mouseenter', this.onMouseEnter);
      });
  };
```
Since your iframe is missing the `ql-video` class it won't match. 

You can either add the `ql-video` class to your blockEmbed, or extend `UnclickableBlotSpec` into a custom class with a suitable selector and include that with the ImageSpec in your options as per [docs](https://github.com/enzedonline/quill-blot-formatter2?tab=readme-ov-file#options)

Something like:

```javascript
import BlotFormatter2, { ImageSpec, UnclickableBlotSpec } from 'quill-blot-formatter2'

Quill.register('modules/blotFormatter2', BlotFormatter2);

class CustomIframeSpec extends UnclickableBlotSpec {
  constructor(formatter: BlotFormatter) {
    super(formatter, 'div.ql-editor iframe');
  }
}

const quill = new Quill(..., {
  modules: {
    ...
    blotFormatter2: {
      image: {
        registerImageTitleBlot: true
      }
      specs: [
        ImageSpec,
        CustomIframeSpec 
      ],
    }
  }
});
```

^ I haven't tested that but I'm 90% sure it's right 😉

I'll be changing that `document.querySelectorAll` to `quill.root.querySelectorAll` next update, shouldn't be searching the whole document.

**Comment by enzedonline** [comment]
> Just a quick other suggestion that I noticed, currently you can't scroll if the cursor is on top of the overlay. Maybe a way to watch scroll and add pointer-events: none; while scrolling to allow the element beneath to scroll?

The more I dig into this, the more I see that this package wasn't designed with scrollable editors in mind. The proxy was also blocking scroll and not updating position after scroll so that it ended up in the wrong position. Then it could also scroll beyond the end of the document causing the window to start scrolling. This also made me see that the proxy is overlaying areas outside of the editor. 

The only way to prevent that was to move the proxy to the quill container then rewrite the positioning formula (did my head in) then listen for wheel events and pass that into the quill root. Scroll doesn't help as it's not fired if the window/ancestor is not in overflow. Can't use pointer events as this enables click events on the iframe. I have my doubts about the necessity of the proxy image, but that's for another time.

I can't replicate your resize issue though and can't see what would cause it. getTargetElement() would only return null if the overlay had been deactivated.

When you say responsive, what is it you want to do? Different behaviour for different screen widths? I'm not sure what you need that can't be addressed with media queries. Maybe send me your custom format, I can try to replicate it and see what's happening.

**Comment by enzedonline** [comment]
This is what's preventing the resize:
```css
.ql-video-inner iframe,
.ql-video-inner object,
.ql-video-inner embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
```
Your setting the iframe width & height to 100% in css so the height/width element attributes have no effect.

I could achieve the same behaviour with this though without needing wrappers. It assumes you want aspect ratio 2:1:

```javascript
const VideoEmbed = Quill.import("formats/video");

class VideoResponsive extends VideoEmbed {
    static create(value) {
        const node = super.create(value);
        node.setAttribute('width', '100%');
        node.style.aspectRatio = 2;
        return node;
    }
}

Quill.register(VideoResponsive);
```

https://github.com/user-attachments/assets/55470cc3-6b24-4f70-a732-65ae058c1413

(My wifi is snail pace ...)

If you want the width to remain relative to the container after resizing instead of px, you could extend your video BlotSpec.onHide() - delete the height attribute as set the width attribute as a percentage of the current quill.root width if it has a px value.

**Comment by enzedonline** [comment]
Great, glad that's working now.

You should really call super in your onHide() as this method takes care of hiding the proxy image and clearing out the unclickable variables.

When I get the v2.1.3 out this week there are a couple of enhancements you can take advantage of - the unclickable selector can be set in the options, the height attribute won't be set if there's an aspect ratio specified (either via style or css) and the responsive class is included in the package and can be registered via options. This would probably eliminate the need for your custom code there.

The `onHide()` change I was suggesting was about keeping width relative to` quill.root` width instead of fixed pixel. You could do that with something like:
```javascript
editorStyle = this.formatter.getComputedStyle(quill.root);
editorWidth = this.formatter.quill.root.clientWidth - 
              parseFloat(editorStyle.paddingLeft) -parseFloat(editorStyle.paddingRight);
this.unclickable.width=`${100 * this.unclickable.clientWidth / internalWidth | 0}%`
```

Maybe I should just add relative resizing as an option.

**Comment by enzedonline** [comment]
I'm still getting there ... I've ended up on a major rewrite to flush out a lot of the buggy behaviour from the original, and also sorting out the iframe proxy situation so that it can work with touch screen. Mostly done, hopefully by this weekend if other demands stay away ...

**Comment by enzedonline** [comment]
There was a lot more to rewrite than first thought, plus other stuff getting in the way.
Not quite finished testing, but I think it's more or less done.
Relative sizing mode (px or %) can be set per blot via toolbar, or for every resize action on every blot. 
Each iframe gets its own proxy now - eliminates all the bugs with the mouse enter event and tracking the cursor, also means it can be used with touch screens now. There's an option to set the style on the proxies which would let you add the z-index there.
You can test the compiled version if you like, downloadable from [here](https://1drv.ms/f/s!AppilyLm3gHit4dluxCw6G0Yh2JcmA?e=EGodlc). Happy to know if you can find any bugs.
The updated readme is there for reference.

**Comment by enzedonline** [comment]
v2.2.0 released now. 

Scroll by wheel or touch now sorted.

You can amend video selector and proxy image style with 
```typescript
  video: {
    selector: 'iframe.ql-video',
    proxyStyle: {}
  }
```
Relative sizing option available (never, by default, by option, or always). For 'by default' or 'by option', a `%` button is added to the toolbar to change modes.

There is a ton of other updates, worth looking at the change log and readme for stuff that might be useful.
