### ISSUE TITLE
Declaration files are not included

### ISSUE THREAD

**Issue by zAlweNy26** [enzedonline/quill-blot-formatter2#5]
When installing the package with NPM, the `.d.ts` files are not included so I get errors from typescript about the missing types.

**Comment by enzedonline** [comment]
The declaration flag was missing in the tsconfig for some reason. Next release will include the declaration files.

**Comment by zAlweNy26** [comment]
Any update on next release date?

**Comment by enzedonline** [comment]
I'm still getting there ... I've ended up on a major rewrite to flush out a lot of the buggy behaviour from the original, and also sorting out the iframe proxy situation so that it can work with touch screen. Mostly done, hopefully by this weekend if other demands stay away ... Hopefully by the weekend if I'm being optimistic

**Comment by enzedonline** [comment]
> Hopefully by the weekend if I'm being optimistic

I was being very optimistic 😉 

Fixed in 2.2.0
